# Quantitative Momentum Strategy

"Momentum investing" means investing in the stocks that have increased in price the most.

For this project, we're going to build an investing strategy that selects the 50 stocks with the highest price momentum. From there, we will calculate recommended trades for an equal-weight portfolio of these 50 stocks.


## Library Imports

The first thing we need to do is import the open-source software libraries that we'll be using in this tutorial.

In [1]:
import numpy as np #The Numpy numerical computing library
import pandas as pd #The Pandas data science library
import requests #The requests library for HTTP requests in Python
import xlsxwriter #The XlsxWriter libarary for 
import math #The Python math module
from scipy import stats #The SciPy stats module

## Importing Our List of Stocks

As before, we'll need to import our list of stocks and our API token before proceeding. Make sure the `.csv` file is still in your working directory and import it with the following command:

In [2]:
stocks= pd.read_csv("sp_500_stocks-Copy1.csv")
from Api_token1 import IEX_CLOUD_API_TOKEN

## Making Our First API Call

It's now time to make the first version of our momentum screener!

We need to get one-year price returns for each stock in the universe. Here's how.

In [3]:
symbol = 'AAPL'
api_url = f'https://sandbox.iexapis.com/stable/stock/{symbol}/stats?token={IEX_CLOUD_API_TOKEN}'
data = requests.get(api_url).json()
data

{'companyName': 'Apple Inc',
 'marketcap': 2348478761842,
 'week52high': 148.44,
 'week52low': 56.52,
 'week52change': 0.7047159654523466,
 'sharesOutstanding': 17190112193,
 'float': 0,
 'avg10Volume': 125795923,
 'avg30Volume': 117583949,
 'day200MovingAvg': 119.69,
 'day50MovingAvg': 137.52,
 'employees': 0,
 'ttmEPS': 3.77,
 'ttmDividendRate': 0.8133399143236723,
 'dividendYield': 0.006223664181396208,
 'nextDividendDate': '2021-01-29',
 'exDividendDate': '2020-10-30',
 'nextEarningsDate': '2021-01-26',
 'peRatio': 35.34687723721367,
 'beta': 1.150943467103891,
 'maxChangePercent': 51.77327610594487,
 'year5ChangePercent': 5.057569894503382,
 'year2ChangePercent': 2.3310286370305726,
 'year1ChangePercent': 0.7744647018030548,
 'ytdChangePercent': 0.009696802478018927,
 'month6ChangePercent': 0.23890710011717223,
 'month3ChangePercent': 0.22140754939535254,
 'month1ChangePercent': 0.009557578130181286,
 'day30ChangePercent': 0.0361917557302909,
 'day5ChangePercent': -0.05719419371218643}

## Parsing Our API Call

This API call has all the information we need. We can parse it using the same square-bracket notation as in the first project of this course. Here is an example.

In [4]:
data['year1ChangePercent']

0.7744647018030548

## Executing A Batch API Call & Building Our DataFrame

Just like in our first project, it's now time to execute several batch API calls and add the information we need to our DataFrame.

We'll start by running the following code cell, which contains some code we already built last time that we can re-use for this project. More specifically, it contains a function called `chunks` that we can use to divide our list of securities into groups of 100.

In [5]:
# Function sourced from 
# https://stackoverflow.com/questions/312443/how-do-you-split-a-list-into-evenly-sized-chunks
def chunks(lst, n):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        yield lst[i:i + n]   
        
symbol_groups = list(chunks(stocks['Ticker'], 100))
symbol_strings = []
for i in range(0, len(symbol_groups)):
    symbol_strings.append(','.join(symbol_groups[i]))
#     print(symbol_strings[i])

my_columns = ['Ticker', 'Price', 'One-Year Price Return', 'Number of Shares to Buy']

Now we need to create a blank DataFrame and add our data to the data frame one-by-one.

In [6]:
final_dataframe = pd.DataFrame(columns = my_columns)

for symbol_string in symbol_strings:
#     print(symbol_strings)
    batch_api_call_url = f'https://sandbox.iexapis.com/stable/stock/market/batch/?types=stats,quote&symbols={symbol_string}&token={IEX_CLOUD_API_TOKEN}'
    data = requests.get(batch_api_call_url).json()
    for symbol in symbol_string.split(','):
        final_dataframe = final_dataframe.append(
                                        pd.Series([symbol, 
                                                   data[symbol]['quote']['latestPrice'],
                                                   data[symbol]['stats']['year1ChangePercent'],
                                                   'N/A'
                                                   ], 
                                                  index = my_columns), 
                                        ignore_index = True)
        
    
final_dataframe

    Ticker    Price One-Year Price Return Number of Shares to Buy
0        A  127.340              0.505904                     N/A
1      AAL   17.575             -0.361133                     N/A
2      AAP  159.540              0.187398                     N/A
3     AAPL  136.000              0.762035                     N/A
4     ABBV  110.360              0.372455                     N/A
..     ...      ...                   ...                     ...
500    YUM  109.400              0.003278                     N/A
501    ZBH  166.220               0.07881                     N/A
502   ZBRA  424.200              0.666288                     N/A
503   ZION   49.600              0.036611                     N/A
504    ZTS  162.500              0.155385                     N/A

[505 rows x 4 columns]

## Removing Low-Momentum Stocks

The investment strategy that we're building seeks to identify the 50 highest-momentum stocks in the S&P 500.

Because of this, the next thing we need to do is remove all the stocks in our DataFrame that fall below this momentum threshold. We'll sort the DataFrame by the stocks' one-year price return, and drop all stocks outside the top 50.

In [7]:
final_dataframe.sort_values('One-Year Price Return', ascending = False, inplace = True)
final_dataframe = final_dataframe[:51]
final_dataframe.reset_index(drop = True, inplace = True)
final_dataframe

   Ticker     Price One-Year Price Return Number of Shares to Buy
0    CARR    39.030              2.223136                     N/A
1     FCX    30.927              1.604246                     N/A
2    NVDA   551.920              1.308852                     N/A
3    ALGN   625.380              1.205806                     N/A
4    PYPL   265.973              1.199003                     N/A
5     ALB   159.293              1.077917                     N/A
6      LB    49.700              0.986326                     N/A
7      DE   323.430              0.956668                     N/A
8    SIVB   514.238              0.943723                     N/A
9    QCOM   154.346               0.92902                     N/A
10    PWR    75.681              0.914129                     N/A
11    WST   299.760              0.872353                     N/A
12   CDNS   142.360              0.866968                     N/A
13    AMD    92.570              0.861793                     N/A
14    URI   267.170              0.801754                     N/A
15   ABMD   336.400              0.790522                     N/A
16   SNPS   275.000              0.784401                     N/A
17   IDXX   495.290              0.782295                     N/A
18   AAPL   136.000              0.762035                     N/A
19    CMG  1533.240              0.757266                     N/A
20   KLAC   293.270              0.750089                     N/A
21   IPGP   243.500              0.732939                     N/A
22    FDX   247.142              0.732249                     N/A
23   EBAY    61.840              0.730418                     N/A
24   AMAT   104.552              0.715969                     N/A
25    NOW   593.660              0.712429                     N/A
26    TGT   190.550              0.706814                     N/A
27   APTV   148.000              0.680757                     N/A
28   TMUS   133.744              0.675552                     N/A
29   TWTR    57.881              0.668299                     N/A
30   ZBRA   424.200              0.666288                     N/A
31   VIAC    53.500              0.664622                     N/A
32   LRCX   532.700              0.663443                     N/A
33   DXCM   414.635              0.656524                     N/A
34   AMZN  3370.000               0.65605                     N/A
35   QRVO   171.030              0.647964                     N/A
36     GM    55.003              0.642554                     N/A
37    BIO   610.120              0.640925                     N/A
38    UPS   164.900              0.635197                     N/A
39   TTWO   211.630              0.634926                     N/A
40   XLNX   141.720              0.632918                     N/A
41   AVGO   468.700              0.621012                     N/A
42   ATVI    93.881              0.614741                     N/A
43   FFIV   199.700               0.60285                     N/A
44   MKTX   584.800              0.595059                     N/A
45   SWKS   183.050              0.590208                     N/A
46    MTD  1224.273              0.588208                     N/A
47    TMO   507.548              0.582076                     N/A
48   TSCO   150.930               0.56317                     N/A
49   HOLX    84.983              0.554636                     N/A
50   KEYS   145.500              0.542925                     N/A

## Calculating the Number of Shares to Buy

Just like in the last project, we now need to calculate the number of shares we need to buy. The one change we're going to make is wrapping this functionality inside a function, since we'll be using it again later in this Jupyter Notebook.

Since we've already done most of the work on this, try to complete the following two code cells without watching me do it first!

In [8]:
def portfolio_input():
    global portfolio_size
    portfolio_size = input("Enter the value of your portfolio:")

    try:
        val = float(portfolio_size)
    except ValueError:
        print("That's not a number! \n Try again:")
        portfolio_size = input("Enter the value of your portfolio:")

portfolio_input()
print(portfolio_size)

Enter the value of your portfolio:200000
200000

In [9]:
position_size = float(portfolio_size) / len(final_dataframe.index)
for i in range(0, len(final_dataframe['Ticker'])):
    final_dataframe.loc[i, 'Number of Shares to Buy'] = math.floor(position_size / final_dataframe['Price'][i])
final_dataframe

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

   Ticker     Price One-Year Price Return Number of Shares to Buy
0    CARR    39.030              2.223136                     100
1     FCX    30.927              1.604246                     126
2    NVDA   551.920              1.308852                       7
3    ALGN   625.380              1.205806                       6
4    PYPL   265.973              1.199003                      14
5     ALB   159.293              1.077917                      24
6      LB    49.700              0.986326                      78
7      DE   323.430              0.956668                      12
8    SIVB   514.238              0.943723                       7
9    QCOM   154.346               0.92902                      25
10    PWR    75.681              0.914129                      51
11    WST   299.760              0.872353                      13
12   CDNS   142.360              0.866968                      27
13    AMD    92.570              0.861793                      42
14    URI   267.170              0.801754                      14
15   ABMD   336.400              0.790522                      11
16   SNPS   275.000              0.784401                      14
17   IDXX   495.290              0.782295                       7
18   AAPL   136.000              0.762035                      28
19    CMG  1533.240              0.757266                       2
20   KLAC   293.270              0.750089                      13
21   IPGP   243.500              0.732939                      16
22    FDX   247.142              0.732249                      15
23   EBAY    61.840              0.730418                      63
24   AMAT   104.552              0.715969                      37
25    NOW   593.660              0.712429                       6
26    TGT   190.550              0.706814                      20
27   APTV   148.000              0.680757                      26
28   TMUS   133.744              0.675552                      29
29   TWTR    57.881              0.668299                      67
30   ZBRA   424.200              0.666288                       9
31   VIAC    53.500              0.664622                      73
32   LRCX   532.700              0.663443                       7
33   DXCM   414.635              0.656524                       9
34   AMZN  3370.000               0.65605                       1
35   QRVO   171.030              0.647964                      22
36     GM    55.003              0.642554                      71
37    BIO   610.120              0.640925                       6
38    UPS   164.900              0.635197                      23
39   TTWO   211.630              0.634926                      18
40   XLNX   141.720              0.632918                      27
41   AVGO   468.700              0.621012                       8
42   ATVI    93.881              0.614741                      41
43   FFIV   199.700               0.60285                      19
44   MKTX   584.800              0.595059                       6
45   SWKS   183.050              0.590208                      21
46    MTD  1224.273              0.588208                       3
47    TMO   507.548              0.582076                       7
48   TSCO   150.930               0.56317                      25
49   HOLX    84.983              0.554636                      46
50   KEYS   145.500              0.542925                      26

## Building a Better (and More Realistic) Momentum Strategy

Real-world quantitative investment firms differentiate between "high quality" and "low quality" momentum stocks:

* High-quality momentum stocks show "slow and steady" outperformance over long periods of time
* Low-quality momentum stocks might not show any momentum for a long time, and then surge upwards.

The reason why high-quality momentum stocks are preferred is because low-quality momentum can often be cause by short-term news that is unlikely to be repeated in the future (such as an FDA approval for a biotechnology company).

To identify high-quality momentum, we're going to build a strategy that selects stocks from the highest percentiles of: 

* 1-month price returns
* 3-month price returns
* 6-month price returns
* 1-year price returns

Let's start by building our DataFrame. You'll notice that I use the abbreviation `hqm` often. It stands for `high-quality momentum`.

In [ ]:
hqm_columns = [
                'Ticker', 
                'Price', 
                'Number of Shares to Buy', 
                'One-Year Price Return', 
                'One-Year Return Percentile',
                'Six-Month Price Return',
                'Six-Month Return Percentile',
                'Three-Month Price Return',
                'Three-Month Return Percentile',
                'One-Month Price Return',
                'One-Month Return Percentile',
                'HQM Score'
                ]

hqm_dataframe = pd.DataFrame(columns = hqm_columns)

for symbol_string in symbol_strings:
#     print(symbol_strings)
    batch_api_call_url = f'https://sandbox.iexapis.com/stable/stock/market/batch/?types=stats,quote&symbols={symbol_string}&token={IEX_CLOUD_API_TOKEN}'
    data = requests.get(batch_api_call_url).json()
    for symbol in symbol_string.split(','):
        hqm_dataframe = hqm_dataframe.append(
                                        pd.Series([symbol, 
                                                   data[symbol]['quote']['latestPrice'],
                                                   'N/A',
                                                   data[symbol]['stats']['year1ChangePercent'],
                                                   'N/A',
                                                   data[symbol]['stats']['month6ChangePercent'],
                                                   'N/A',
                                                   data[symbol]['stats']['month3ChangePercent'],
                                                   'N/A',
                                                   data[symbol]['stats']['month1ChangePercent'],
                                                   'N/A',
                                                   'N/A'
                                                   ], 
                                                  index = hqm_columns), 
                                        ignore_index = True)
        
hqm_dataframe.columns

## Calculating Momentum Percentiles

We now need to calculate momentum percentile scores for every stock in the universe. More specifically, we need to calculate percentile scores for the following metrics for every stock:

* `One-Year Price Return`
* `Six-Month Price Return`
* `Three-Month Price Return`
* `One-Month Price Return`

Here's how we'll do this:

In [ ]:
time_periods = [
                'One-Year',
                'Six-Month',
                'Three-Month',
                'One-Month'
                ]

for row in hqm_dataframe.index:
    for time_period in time_periods:
        hqm_dataframe.loc[row, f'{time_period} Return Percentile'] = stats.percentileofscore(hqm_dataframe[f'{time_period} Price Return'], hqm_dataframe.loc[row, f'{time_period} Price Return'])/100

# Print each percentile score to make sure it was calculated properly
for time_period in time_periods:
    print(hqm_dataframe[f'{time_period} Return Percentile'])

#Print the entire DataFrame    
hqm_dataframe

## Calculating the HQM Score

We'll now calculate our `HQM Score`, which is the high-quality momentum score that we'll use to filter for stocks in this investing strategy.

The `HQM Score` will be the arithmetic mean of the 4 momentum percentile scores that we calculated in the last section.

To calculate arithmetic mean, we will use the `mean` function from Python's built-in `statistics` module.

In [ ]:
from statistics import mean

for row in hqm_dataframe.index:
    momentum_percentiles = []
    for time_period in time_periods:
        momentum_percentiles.append(hqm_dataframe.loc[row, f'{time_period} Return Percentile'])
    hqm_dataframe.loc[row, 'HQM Score'] = mean(momentum_percentiles)

## Selecting the 50 Best Momentum Stocks

As before, we can identify the 50 best momentum stocks in our universe by sorting the DataFrame on the `HQM Score` column and dropping all but the top 50 entries.

In [ ]:
hqm_dataframe.sort_values(by = 'HQM Score', ascending = False)
hqm_dataframe = hqm_dataframe[:51]

## Calculating the Number of Shares to Buy

We'll use the `portfolio_input` function that we created earlier to accept our portfolio size. Then we will use similar logic in a `for` loop to calculate the number of shares to buy for each stock in our investment universe.

In [ ]:
portfolio_input()

In [ ]:
position_size = float(portfolio_size) / len(hqm_dataframe.index)
for i in range(0, len(hqm_dataframe['Ticker'])-1):
    hqm_dataframe.loc[i, 'Number of Shares to Buy'] = math.floor(position_size / hqm_dataframe['Price'][i])
hqm_dataframe

## Formatting Our Excel Output

We will be using the XlsxWriter library for Python to create nicely-formatted Excel files.

XlsxWriter is an excellent package and offers tons of customization. However, the tradeoff for this is that the library can seem very complicated to new users. Accordingly, this section will be fairly long because I want to do a good job of explaining how XlsxWriter works.

In [ ]:
writer = pd.ExcelWriter('momentum_strategy.xlsx', engine='xlsxwriter')
hqm_dataframe.to_excel(writer, sheet_name='Momentum Strategy', index = False)

## Creating the Formats We'll Need For Our .xlsx File

You'll recall from our first project that formats include colors, fonts, and also symbols like % and $. We'll need four main formats for our Excel document:

* String format for tickers
* \$XX.XX format for stock prices
* \$XX,XXX format for market capitalization
* Integer format for the number of shares to purchase

Since we already built our formats in the last section of this course, I've included them below for you. Run this code cell before proceeding.

In [ ]:
background_color = '#0a0a23'
font_color = '#ffffff'

string_template = writer.book.add_format(
        {
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

dollar_template = writer.book.add_format(
        {
            'num_format':'$0.00',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

integer_template = writer.book.add_format(
        {
            'num_format':'0',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

percent_template = writer.book.add_format(
        {
            'num_format':'0.0%',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

In [ ]:
column_formats = { 
                    'A': ['Ticker', string_template],
                    'B': ['Price', dollar_template],
                    'C': ['Number of Shares to Buy', integer_template],
                    'D': ['One-Year Price Return', percent_template],
                    'E': ['One-Year Return Percentile', percent_template],
                    'F': ['Six-Month Price Return', percent_template],
                    'G': ['Six-Month Return Percentile', percent_template],
                    'H': ['Three-Month Price Return', percent_template],
                    'I': ['Three-Month Return Percentile', percent_template],
                    'J': ['One-Month Price Return', percent_template],
                    'K': ['One-Month Return Percentile', percent_template],
                    'L': ['HQM Score', integer_template]
                    }

for column in column_formats.keys():
    writer.sheets['Momentum Strategy'].set_column(f'{column}:{column}', 20, column_formats[column][1])
    writer.sheets['Momentum Strategy'].write(f'{column}1', column_formats[column][0], string_template)

## Saving Our Excel Output

As before, saving our Excel output is very easy:

In [ ]:
writer.save()